### ISSUE TITLE
IndexError while running Pool-Hmm

### ISSUE THREAD

**Issue by inescmiranda** [magicDGS/PoolHMM#1]
Hi, I'm running Pool-hmm with Python v. 2.7 and I'm getting this error message:

Traceback (most recent call last):
  File "/usr/local/bin/pool-hmm/1.4.3/pool-hmm.py", line 313, in <module>
    prediction(k,prefix)
  File "/usr/local/bin/pool-hmm/1.4.3/Modules/pred.py", line 27, in prediction
    pred = hmm_viterbi(T,E,mu0)
  File "/usr/local/bin/pool-hmm/1.4.3/Modules/hmm_viterbi.py", line 41, in hmm_viterbi
    pred[i] = Zarg[pred[i+1]-1, i+1]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

I'm new to this kind of software and analyses so I don't know how to fix this. Any ideas that could help me?

Thanks!

**Comment by magicDGS** [comment]
Hi @inndcm - this is not the original repository for the Pool-HMM software, but just a copy of version 1.4.3 with MacOS support (I use OSX and it wasn't working for it). I included it in my GitHub repository to allow other users with the same problem to use the version.

I don't know the details of the implementation itself, nor the possible bugs or problems. I recommend to contact the original authors in one of this places:

* https://qgsp.jouy.inra.fr/index.php?option=com_content&view=article&id=56&Itemid=63
* https://forge-dga.jouy.inra.fr/projects/pool-hmm

In addition, it looks like this repository has an old version of the software (1.4.3 instead of the latest 1.4.4). The problem might be fixed there, I guess. I will try to update this repository with version 1.4.4 checking the differences with the current one.

**Comment by magicDGS** [comment]
I research a bit in the original code and I found that the original authors fixed the issue in the version 1.4.4. I updated the repository to contain that fix, and I started to create custom releases for this repo.

This should be fixed now. I am happy that this is useful for someone. Thanks!

**Comment by magicDGS** [comment]
For future reference: fixed in #2, and version with the fix in [version 1.4.4-custom.1](https://github.com/magicDGS/PoolHMM/releases/tag/v1.4.4-custom.1)
